import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "LockHost-Auth",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}
function AuthLayout({ children }: RootLayoutProps) {
  return (
    <div className="bg-auth-hero bg-cover bg-center h-full flex items-center justify-center">
      {children}
    </div>
  );
}

export default AuthLayout;
