import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Brand from "@/components/Brand";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LockHost",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}
function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`flex flex-col ` + archivo.className}>
        <Header />
        <div className="flex flex-col flex-1">{children}</div>
        <Brand />
      </body>
    </html>
  );
}

export default RootLayout;
